bldr:
    name: sctr/content
    description: CMS for the VideosZ website
    profiles:
        dev:
            description: Local Profile
            jobs:
                - testLocal
                - watch
        default:
            description: 'Development Profile'
            jobs:
                - prepare
                - lint
                - phpcs
                - testLocal
    jobs:
        prepare:
            description: 'Cleans up old builds and prepares the new one'
            tasks:
                -
                    type: filesystem:remove
                    continueOnError: true
                    files: [build/coverage, build/logs, build/behat, app/cache, app/logs]
                -
                    type: filesystem:mkdir
                    continueOnError: true
                    files: [build/coverage, build/logs, build/behat, app/cache, app/logs]
                -
                    type: filesystem:touch
                    files: [build/coverage/Index.html]
                -
                    type: notify
                    message: Prepare Task Finished
        lint:
            description: 'Lints the files of the project'
            tasks:
                -
                    type: apply
                    src:
                        - { path: [src, web, features, app/config], files: '*.php', recursive: true] }
                    executable: php
                    arguments: [-l]

        phpcs:
            description: 'Runs the PHP Code Sniffer'
            tasks:
                -
                    type: exec
                    continueOnError: true
                    executable: php
                    arguments:
                        - bin/phpcs
                        - --standard=phpcs.xml
                        - --ignore=src/Resources/private
                        - --report=full
                        - src/
                -
                    type: exec
                    continueOnError: true
                    output: /dev/null
                    append: false
                    executable: php
                    arguments:
                        - bin/phpcs
                        - --standard=phpcs.xml
                        - --report=checkstyle
                        - --ignore=src/Resources/private
                        - --report-file=build/logs/checkstyle.xml
                        - src/
        testLocal:
            description: 'Runs the PHPUnit Tests'
            tasks:
                -
                    type: exec
                    continueOnError: true
                    executable: ./bin/behat
                    arguments:
                        - --profile=local
                        - --ansi
        watch:
            tasks:
                -
                    type: watch
                    task: testLocal
                    src:
                        - { path: [src, features], files: '*', recursive: true }